---

# Default state for all rules
default: true

# MD001/heading-increment - Heading increment
# Don't enforce that top level headings must increment by 1
MD001: false

# MD003/heading-style/header-style - Heading style
MD003:
  # Enforce the ATX-closed style of header
  style: "atx"

# MD004/ul-style - Unordered list style
MD004:
  # Enforce dashes for unordered lists
  style: "dash"

# MD010/hard-tabs - Hard tabs
# Don't enforce that hard tabs are not used
MD010: false

# MD013/line-length - Line length
MD013: false

# MD024/no-duplicate-heading/no-duplicate-header - Multiple headings with the
# same content
MD024:
  # Allow headers with the same content as long as they are not in the same
  # parent heading
  allow_different_nesting: true

# MD029/ol-prefix - Ordered list item prefix
MD029: false

# MD033/no-inline-html - Inline HTML
MD033: false

# MD034/no-bare-urls - Bare URLs
MD034: false

# MD035/hr-style - Horizontal rule style
MD035:
  # Enforce dashes for horizontal rules
  style: "---"

# MD041/first-line-h1 - First line in file should be a top level heading
MD041: false

# MD046/code-block-style - Code block style
MD046:
  # Enforce the fenced style for code blocks
  style: "fenced"

# MD049/emphasis-style - Emphasis style should be consistent
MD049:
  # Enforce asterisks as the style to use for emphasis
  style: "asterisk"

# MD050/strong-style - Strong style should be consistent
MD050:
  # Enforce asterisks as the style to use for strong
  style: "asterisk"
